export const HOME = 'HomeScreen';
export const BOTTOM_TABS = 'BottomTabs';
export const EXPLORE_BRAND = 'ExploreBrand';
export const NOTIFICATION = 'Notification';
export const INTRODUCTION = 'Introduction';
export const LOGIN = 'Login';
export const OTP = 'Otp';
export const FIND_RESTAURANT_MAP = 'FIND_RESTAURANT_MAP';



//EatsEzy
export const PROFILE = 'PROFILE';
export const SIGNUP_SCREEN = 'SIGNUP_SCREEN';
export const RESTAURANTDETAIL_SCREEN = 'RESTAURANTDETAIL_SCREEN';
export const RESTAURANTS_SCREEN = 'RESTAURANTS_SCREEN';
export const SEARCH_SCREEN = 'SEARCH_SCREEN';
export const BOOKINGDETAIL_SCREEN = 'BOOKINGDETAIL_SCREEN';
export const EDITBOOKING = 'EDITBOOKING';

export const MYRESERVESION_SCREEN = 'MYRESERVESION_SCREEN';
export const CREATEENQUIRY_SCREEN = 'CREATEENQUIRY_SCREEN';
export const RESERVED_SCREEN = 'RESERVED_SCREEN';
export const EDITPROFILE_SCREEN = 'EDITPROFILE_SCREEN';
export const EATSEZY_SCREEN = 'EATSEZY_SCREEN';
export const ENQUIRIES_SCREEN = 'ENQUIRIES_SCREEN';
export const MYPREFERENCES_SCREEN = 'MYPREFERENCES_SCREEN';
export const REVIEW_GIVEN_SCREEN = 'REVIEW_GIVEN_SCREEN';
export const TRANSACTION_SCREEN = 'TRANSACTION_SCREEN';
export const INQUIRES_SCREEN = 'INQUIRES_SCREEN';
export const WALLET_SCREEN = 'WALLET_SCREEN';
export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
export const MYFAVOURITE_SCREEN = 'MYFAVOURITE_SCREEN';
export const REVIEW_SCREEN = 'REVIEW_SCREEN';
export const PDF_SCREEN = 'PDF_SCREEN';
export const RESTAURANT_REVIEW_SCREEN = 'RESTAURANT_REVIEW_SCREEN';












